### ISSUE TITLE
Query - RLScore

### ISSUE THREAD

**Issue by vinayakumarr** [aatapa/RLScore#1]
I have seen your application. First of all thanks for sharing and i would like to know what is the difference between the GURLS MIT and your package and also where we find few examples for your package. Because i prefer python over matlab and i tried once GURLS for my data set and due to memory i was not able to do classification. I think your package solve my problem. Also is there any sample example for multi-class classification?

**Comment by ajairo** [comment]
Tutorials for RLScore can now be found online at: http://staff.cs.utu.fi/~aatapa/software/RLScore/

A simple example about multi-class classification can be found at:
http://staff.cs.utu.fi/~aatapa/software/RLScore/tutorial_regression.html#tutorial-5-multi-target-learning

The example uses a linear kernel. If you want to use a non-linear kernel, check also the kernel examples such as: 

http://staff.cs.utu.fi/~aatapa/software/RLScore/tutorial_regression.html#learning-nonlinear-predictors-using-kernels

And if you have so much data that the kernel matrix does not fit into memory (i.e. roughly much more than 10 K instances on a modern desktop), you can use the reduced set approximation, see tutorial:

http://staff.cs.utu.fi/~aatapa/software/RLScore/tutorial_regression.html#tutorial-4-reduced-set-approximation

Compared to GURLS, the RLScore module RLS (Regularized-least-squares) implements pretty much the same fast algorithms (fast leave-one-out, multi-target learning, fast regularization...). However, RLScore implements also a number of other fast cross-validation algorithms for RLS  and also a large variety of other learning algorithms for feature selection, ranking, clustering, pair-input learning etc. (see tutorials).

**Comment by vinayakumarr** [comment]
How to get precision, recall, f-measure, true positive rate, false positive rate for multi class classification problems
