### ISSUE TITLE
Multi class classification statistical measures

### ISSUE THREAD

**Issue by vinayakumarr** [aatapa/RLScore#2]
How to get precision, recall, f-measure, true positive rate, false positive rate for multi class classification problems

**Comment by ajairo** [comment]
Currently, RLScore does not include code for computing these performance measures for multi-class data. While this may change in future versions, at the moment the easiest way to compute these would be to use the implementations of these performance measures available in the scikit-learn package.

For example regarding the multi-class learning example given in:

http://staff.cs.utu.fi/~aatapa/software/RLScore/tutorial_regression.html#tutorial-5-multi-target-learning

the easiest way to get these performance measures for the test set would be first to transform the one-vs-all encoded predictions made by RLScore as follows:

#import a utility function from rlscore
from rlscore.utilities.multiclass import from_one_vs_all

#At first the predictions are in one-vs-all format
P = learner.predict(X_test)
#Let's map the predictions to running class numbers
P = from_one_vs_all(P)


And after this, compute precision, recall, tpr etc. between Y_test and P using the sklearn functions described here:

http://scikit-learn.org/stable/modules/classes.html#module-sklearn.metrics

**Comment by vinayakumarr** [comment]
Thanks. For binary classification, I have used your program with my data as labelled 1 and -1 But it is predicting label as -1, 1 0. The accuracy on test data showed 99% in RLScore but when i saved the predicted and expected label in scikit it showed 56%. Could you please tell me why it is showing this error.

**Comment by vinayakumarr** [comment]
Traceback (most recent call last):
  File "check.py", line 17, in <module>
    print(accuracy_score(Y_train, Y_test))
  File "/usr/local/lib/python2.7/dist-packages/sklearn/metrics/classification.py", line 172, in accuracy_score
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/metrics/classification.py", line 82, in _check_targets
    "".format(type_true, type_pred))
ValueError: Can't handle mix of binary and continuous

print("test set accuracy %f" %accuracy(Y_test, P_test)) // it worked
Showing this error for for sklearn accuracy_score print(accuracy_score(Y_test, P_test))

**Comment by ajairo** [comment]
Without seeing the code it is difficult to say what exactly is the problem. If this was produced on binary classification data, maybe the problem is that RLS regression produces real-valued predictions rather than discrete class values?

So if you have

from sklearn.metrics import accuracy_score

Y = [1,1,1,-1,-1]
P = [0.3, 0.2, -0.1, -1.2, -0.8]
accuracy_score(Y, P)

You get the same error message as in your example?

FIX:
Binarize the predictions before computing binary classification accuracy, i.e.

import numpy as np
P = np.array(P)
#Transform predictions larger than 0 to 1, and smaller or equal to -1
P = np.where(P>0, 1, -1)
accuracy_score(Y, P)

If you have further problems, you can also e-mail us a minimal example of your code that produces errors, see our e-mail addresses on the project front page.

**Comment by vinayakumarr** [comment]
Thamk you. 
In scikit we can get predict_proba for getting probabilites. I want to get probabilities values for binary classification in RLScore. How to do this?

**Comment by vinayakumarr** [comment]
How to get the probabilites in prediction instead of class labels

**Comment by ajairo** [comment]
All the RLScore methods predict real-valued scores.

Methods like Platt's scaling (see e.g. http://fastml.com/classifier-calibration-with-platts-scaling-and-isotonic-regression/ ) could be used to transform the predictions to probability estimates, but this kind of transformations are not currently implemented in the software.

**Comment by vinayakumarr** [comment]
How to cite your library?

**Comment by ajairo** [comment]
For citing the library, please cite the recent software paper (see http://jmlr.org/papers/v17/16-470.htm )  at JMLR:

RLScore: Regularized Least-Squares Learners
T Pahikkala, A Airola
Journal of Machine Learning Research 17 (221), 1-5, 2016.

Bibtex citation:

@article{JMLR:v17:16-470,
  author  = {Tapio Pahikkala and Antti Airola},
  title   = {RLScore: Regularized Least-Squares Learners},
  journal = {Journal of Machine Learning Research},
  year    = {2016},
  volume  = {17},
  number  = {221},
  pages   = {1-5},
  url     = {http://jmlr.org/papers/v17/16-470.html}
}
