### ISSUE TITLE
Import of numpy in setup.py causing build to break

### ISSUE THREAD

**Issue by ankitvgupta** [aatapa/RLScore#7]
Hello, I'm looking to install your package in a fresh conda environment (as in no existing dependencies, including no numpy). However, since numpy is in your setup.py file, I cannot install this package without first separately installing numpy. Is there any way to remove this dependency? I haven't seen it in other packages that use numpy as a requirement of their own. Thanks!

https://github.com/aatapa/RLScore/blob/0d735a1046ff7f1c0dbee10e98f7224b14f876d3/setup.py#L3

**Comment by ajairo** [comment]
Hi! RLScore library is dependant on numpy and cannot be used without it being installed. Further,  the setup script needs to import numpy since the function np.include() is needed for locating the numpy *.h header files that are required for compiling the RLScore cython extensions.
